models/Provincias.php
<?php

namespace app\models;

use Yii;
/**
 * This is the model class for table "provincias".
 *
 * @property string|null $autonomia
 * @property string|null $provincia
 * @property int|null $poblacion
 * @property int|null $superficie
 */
class Provincias extends \yii\db\ActiveRecord
{
    public $popmin;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'provincias';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['poblacion', 'superficie'], 'integer'],
            [['autonomia', 'provincia'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'autonomia' => 'Autonomia',
            'provincia' => 'Provincia',
            'poblacion' => 'Poblacion',
            'superficie' => 'Superficie',
        ];
    }
}

controllers/ProvinciasController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Provincias;
use yii\data\ActiveDataProvider;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ProvinciasController implements the CRUD actions for Provincias model.
 */
class ProvinciasController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Provincias models.
     * @return mixed
     */
    public function actionIndex()
    {
        $dataProvider = new ActiveDataProvider([
            'query' => Provincias::find(),
        ]);

        return $this->render('index', [
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Provincias model.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Provincias model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Provincias();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->provincia]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Provincias model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->provincia]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    /**
     * Deletes an existing Provincias model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param string $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Provincias model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param string $id
     * @return Provincias the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Provincias::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

use yii\data\SqlDataProvider;
use yii\data\ActiveDataProvider;
use app\models\Provincias;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * Displays contact page.
     *
     * @return Response|string
     */
    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        }
        return $this->render('contact', [
            'model' => $model,
        ]);
    }

    /**
     * Displays about page.
     *
     * @return string
     */
    public function actionAbout()
    {
        return $this->render('about');
    }
    
    public function actionConsultadao()
    {
        $dataProvider = new SqlDataProvider([
            'sql'=>'SELECT provincia FROM provincias 
                WHERE poblacion = (
                  SELECT MIN(c3.poblacion) as popmin FROM
                    (
                    SELECT poblacion, provincia, autonomia FROM provincias 
                      WHERE autonomia =  
                      (
                          SELECT c1.autonomia FROM 
                        (
                        SELECT autonomia, superficie FROM provincias 
                          GROUP BY autonomia HAVING COUNT(provincia) > 2
                        )c1

                        WHERE c1.superficie = 
                        (
                          SELECT MAX(c2.superficie) FROM 
                            (
                              SELECT autonomia, superficie FROM provincias 
                              GROUP BY autonomia HAVING COUNT(provincia) > 2
                            )c2
                        )
                      )
                    )c3
                )',
            'totalCount'=>5,
            'pagination'=>['pageSize' => 5,]
        ]);
        
        return $this->render("resultado", [
           "resultado"=>$dataProvider,
            "campos"=>['provincia'],
            "titulo"=>"Consulta provincias con DAO",
            "enunciado"=>"La provincia mas despoblada de la autonomia menos extensa teniendo en cuenta solo las autonomias"
            . "de más de 2 provincias (con DAO sin utilizar la clausula LIMIT)",
            "sql"=>"Para llegar a esta consulta he hecho los siguiente:"
            . "1: agrupe las autonomias por su superficie, teniendo en cuenta que solo aparezcan las que tienen mas de 2 provincias."
            . "2: a base de estos resultados, busce la superficie mas alta de todas."
            . "3: con la superficie mas alta, busce cual de las autonomias tiene esa superficia"
            . "4: a partir de aqui buscamos datos de autonomias usando los datos anteriores. Buscamos la poblacion de cada provincia de cada autonomia"
            . "5: despues, con estos resultados, recogemos la poblacion mas pequeña"
            . "6: finalmente, simplemente miramos con un WHERE cual provincia tiene esa poblacion.",
        ]);
    }
}

views/provincias/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\Provincias */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="provincias-form">

    <?php $form = ActiveForm::begin(); ?>

    <?= $form->field($model, 'autonomia')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'provincia')->textInput(['maxlength' => true]) ?>

    <?= $form->field($model, 'poblacion')->textInput() ?>

    <?= $form->field($model, 'superficie')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton('Save', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/provincias/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Provincias */

$this->title = 'Create Provincias';
$this->params['breadcrumbs'][] = ['label' => 'Provincias', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="provincias-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/provincias/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Provincias';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="provincias-index">


    <div class="jumbotron">
        <h1>Consultas con DAO y ORM</h1>
    </div>

    <div class="body-content">
        <div class="row">
            <!--
            -->
            
            <div class="col-sm-6 col-md-4">
                <div class="thumbnail">
                    <h3>consulta 1</h3>
                    <P>La provincia mas despoblada de la autonomia menos extensa teniendo en cuenta solo las autonomias"
            . "de más de 2 provincias (con DAO sin utilizar la clausula LIMIT)</P>
                    <p>
                        <?= Html::a('DAO', ['site/consultadao'], ['class' => 'btn btn-primary'])?> 
                    </p>
                </div>
            </div>
        </div>
    </div>


</div>

views/provincias/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\Provincias */

$this->title = 'Update Provincias: ' . $model->provincia;
$this->params['breadcrumbs'][] = ['label' => 'Provincias', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->provincia, 'url' => ['view', 'id' => $model->provincia]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="provincias-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/provincias/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\Provincias */

$this->title = $model->provincia;
$this->params['breadcrumbs'][] = ['label' => 'Provincias', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="provincias-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->provincia], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->provincia], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'autonomia',
            'provincia',
            'poblacion',
            'superficie',
        ],
    ]) ?>

</div>